### ISSUE TITLE
Latest Update 1.1.0 Broken

### ISSUE THREAD

**Issue by dmkjr** [adamtootle/staff-directory#13]
Evening,
Just writing for a few issues with the latest release.  I loved the idea of single author pages with biographies, but it failed.

The latest update created issues with JQUERY items as well as broke other custom_post_type layouts.  I saw users saying they were receiving a 500 error.  I wasn't able to duplicate that.

I'm not sure if it's because of it killing layout items, but also shortcodes for Staff Directory plugin did not function any longer after update.

**Comment by TurqDevDesign** [comment]
Hi @dmkjr, sorry to hear you're having issues. I'm not the owner of this repo, but I did contribute to much of the last update. Would you be able to give any more-detailed information? Any console errors or PHP error logs would be much appreciated. You said you couldn't duplicate the 500 error, but if you could point me to any of the reports of this, it could be helpful. As well, my shortcodes are working perfectly, what shortcode are you trying?

**Comment by dmkjr** [comment]
@TurqDevDesign Austin, thanks for getting back with me.

So, as soon as I update the Staff Directory Plugin, I can see that the biography pages are functional, although it's stripping out my Staff Directory shortcodes.

I have a backup if you would like to see what I'm talking about.  I can update the script and show you for some possible debugging?

https://cityofhanahan.com is our website.  Feel free to email me at bigdk3@gmail.com if that makes communication easier.  I've been waiting a long time for these new features.

**Comment by dmkjr** [comment]
@TurqDevDesign Currently I have the previous version installed.  After you take a look, I'll update.

**Comment by adamtootle** [comment]
Yeah some log output would be useful. Also what version of PHP you're running. I saw some reports of the 500 errors but haven't had a chance to look much into it other than reading that line causing it doesn't play well on anything older than PHP 5.5.

**Comment by dmkjr** [comment]
I have PHP7 enabled on the server.  I'm not getting the 500 errors.  

If you take a look here, https://cityofhanahan.com/government/human-resources/ , you will see in the left sidebar an employee information here, which is handled from your Staff Directory plugin.  When I update the plugin, these no longer appear and when I visit a gallery (https://www.cityofhanahan.com/galleries) from the previous link, the custom_post_type is severely damaged.  It stops the images from loading and removes most of the CSS or doesn't allow the CSS to load.  

I'm not sure how to get log output from this?  I can update quickly to show you the errors if that helps?

**Comment by adamtootle** [comment]
Interesting. It's possible that even though things are messing up it may not be triggering any sort of errors that would get logged. Are you using a plugin for the galleries? Or is that custom?

**Comment by dmkjr** [comment]
It's custom.  It's part of the theme we are using which is called TownPress from Envato.  I can send you the theme if that helps too?  I'm not sure if it's causing issues with the theme or if its conflicting with something else.  I'm here to help.  Been looking forward to this feature for awhile.

**Comment by TurqDevDesign** [comment]
If you could update to the new version now, I'd like to see what's happening.

**Comment by dmkjr** [comment]
Okay, give me about a minute and a half.

**Comment by adamtootle** [comment]
@TurqDevDesign I'm pretty sure we're going to have to tweak `StaffDirectory::load_profile_template()`. I'm trying to troubleshoot it now.

**Comment by TurqDevDesign** [comment]
@adamtootle Let me take a look

**Comment by dmkjr** [comment]
Okay, it's been updated.

You can see from this link https://cityofhanahan.com/galleries/2016-senior-thanksgiving-lunch/

that it destroyed the gallery.  Also the shortcodes aren't working on pages like https://cityofhanahan.com/government/human-resources/

**Comment by TurqDevDesign** [comment]
Strange.. @adamtootle I don't believe it's an issue with load_profile_template(), all that does is check if it is a single post with the type of 'staff'. And then load the set file. Are you seeing something different?

**Comment by adamtootle** [comment]
@TurqDevDesign check that last commit. `single-staff.php` in the plugin directory was overriding non-staff post types for me locally. I added a check around it and it seems to be working as expected. Possibly a bug with `is_singular()` or something.

**Comment by TurqDevDesign** [comment]
@adamtootle I see what you did, makes sense.

**Comment by adamtootle** [comment]
@TurqDevDesign actually, probably not a bug with `is_singular()`, but we were definitely never returning `$original` in that function. Even if `if(is_singular('staff'))` didn't pass. Could you double check and make sure that works on your end? I'll issue an update tonight.

@dmkjr feel free to revert to the working version for now so things don't stay messed up. I'm looking at issuing an update to wordpress.org shortly.

**Comment by dmkjr** [comment]
@adamtootle Thanks for the quick work.  I'll revert now.

**Comment by TurqDevDesign** [comment]
@adamtootle I think I figured it out, `return STAFF_LIST_TEMPLATES . $default_file_name;` needs to be inside the `if(is_singular('staff'))`. And then add `return $original;` at then end of  `load_profile_template()`

**Comment by adamtootle** [comment]
@TurqDevDesign yep. I pushed that up already. Just wanted to see if you could verify it's working on your end before I send it off to wordpress.org.

**Comment by adamtootle** [comment]
To clarify, it's working for me. Just wanted you to see it since that's part of what you wrote.

**Comment by TurqDevDesign** [comment]
Yes, looks like it's working properly. That still doesn't seem to explain the shortcode not working though.

**Comment by dmkjr** [comment]
If you two need me to test a package before it goes to Wordpress, just let me know.  I'll be working on things for a few hours this evening.

**Comment by TurqDevDesign** [comment]
@dmkjr which staff template are you using? list, grid, or custom?

**Comment by dmkjr** [comment]
Custom.

**Comment by TurqDevDesign** [comment]
If you switch back to the new version, go to your settings, and then save, might that solve the shortcode not working issue?

**Comment by dmkjr** [comment]
Is there a newer version to try with this?  I known he made a commit.  Either way, I can test that if desired.

**Comment by TurqDevDesign** [comment]
Not in the Wordpress listings yet, but it has been committed on here. You can download the zip from here, rename it to staff-directory.zip, and then do a manual install if you'd like.

**Comment by dmkjr** [comment]
Could I just override the files via FTP?

**Comment by adamtootle** [comment]
Yeah you can install it manually from here to try the latest changes. You could also just clone it from here if you git on your server. Probably a good point that the last two commits _shouldn't_ have affected the shortcode. But at the moment I'm not sure why the shortcode wouldn't be working. It's working as expected on my end.

**Comment by dmkjr** [comment]
Testing now, will report back shortly.

**Comment by dmkjr** [comment]
Okay, Custom_post_type issue has been fixed.  Shortcodes are still broken.

**Comment by TurqDevDesign** [comment]
Like Adam said, you can just clone the repo and add the files to your plugins file, just make sure to remove the other staff-directory folder. It won't overwrite it because the clone will be named staff-directory-master.

**Comment by TurqDevDesign** [comment]
Have you tried what I suggested? Go to settings > save. And see if that helps

**Comment by dmkjr** [comment]
I did.  No dice.

**Comment by adamtootle** [comment]
@dmkjr can you drop the shortcode in here as you entered it via the WP editor? It's possible one of the options getting passed in is breaking something.

**Comment by TurqDevDesign** [comment]
How about if you make a new custom template, copy your code from the first template, and then use that one?

**Comment by dmkjr** [comment]
[staff-directory cat="267" template=custom_4]

**Comment by dmkjr** [comment]
I copied the content from custom4 and created a custom7 and no dice.

**Comment by dmkjr** [comment]
Also, for clarity.  The shortcode is inserted into a text widget that loads on each page.  Not sure if that changes anything, but that's how I control which Staff category is displayed on what page.

**Comment by TurqDevDesign** [comment]
Ok, well at the very least that rules out issues with how the content is being stored and retrieved has changed.

**Comment by TurqDevDesign** [comment]
If you create a new, private page, and use the shortcode in the page body, will that work? It could be an issue with your text widget.

**Comment by adamtootle** [comment]
Good idea on trying it in the page content.

Without getting any sort of server error it's possible that the shortcode is executing properly as far as WP is concerned and just not returning output as expected. If it works in the page content, can you remove the two options inside the text widget and just use `[staff-directory]`? If you get any sort of output there then one of the options make have a bug.

**Comment by dmkjr** [comment]
I created a page, added shortcode, no dice.  I added text after shortcode to see if the shortcode was stopping code to parse.  I saw the text fine.

**Comment by dmkjr** [comment]
Well good news, there is output with [staff-directory]  

Just gives me a single picture frame with no image and "private:test" and Phone:  And Email:

**Comment by adamtootle** [comment]
Ah. This might be related to #10. That was another PR allowing multiple categories to be combined using AND logic. Does adding the `template` option back in still get you some output? That would verify that the `cat` option is the culprit here.

**Comment by dmkjr** [comment]
Yes, still have output with template added in.  When I add "cat" it makes the shortcode not appear at all.

**Comment by adamtootle** [comment]
Ok sweet - that was expected. Working on a fix now.

**Comment by TurqDevDesign** [comment]
@adamtootle, what are your thoughts? Something in `$query_args['tax_query']`?

**Comment by adamtootle** [comment]
@TurqDevDesign yeah. Basically the recent change expected a comma-separated list. I missed that when I merged it. It now checks to see if cat is numeric and responds accordingly. I kinda want to redo that whole part because passing in multiple category IDs will still break. The list is expected to be slugs. But I just pushed a fix that will fix this particular issue.

@dmkjr Can you check that last push and see if it works with the `cat` option back in?

**Comment by dmkjr** [comment]
Certainly, testing now.

**Comment by dmkjr** [comment]
Well, its giving something different, but not what's expected.

https://cityofhanahan.com/government/administration/purchasing/

The shortcode is displaying the "featured image" and not the staff member image and shows no other content from that staff member.

**Comment by adamtootle** [comment]
Ok. I think we're back around to a template issue now. We're getting close! Are you passing a template into that shortcode that's not getting used? Or is it using the default option and that's not working?

**Comment by dmkjr** [comment]
Well it appears that not all the shortcodes are working :/  hmm.  https://cityofhanahan.com/government/police-department/

that page, none of the shortcode is functioning on the left panel.

[staff-directory cat="322,278" template=custom_4]

That's the exact shortcode that is used on that page with an active template.

**Comment by adamtootle** [comment]
Ha ok. That's the exact scenario I mentioned a couple of comments ago about multiple category IDs. Ok..one more commit incoming. Let me rewrite that part. We'll have this working before it's over with! Thanks a ton to you guys for helping work through this.

**Comment by dmkjr** [comment]
No problem at all.  I have some good ideas for your plugin too.  After using 5 or 6 other ones for a few years, this one has worked out to be the best so far.  And, especially if we have someone willing to work through issues.  I appreciate it.

**Comment by TurqDevDesign** [comment]
@adamtootle I think I have an idea of what's going on, in the previous version we simply had 
`array(
    'taxonomy' => 'staff_category',
    'terms'    => array( $cat )
)`

and `'field' => 'term_id'` is the default in that case. 
Now we have `'field' => 'slug'`.

It's not showing anything because what we're querying for simply doesn't exist. Those numbers are the ID numbers, not the slugs.

**Comment by adamtootle** [comment]
@TurqDevDesign yep. There's also an `operator` option there now. I'm rewriting that whole section to maintain support for the newer functionality, as well as restore what's broken. It's definitely that part that's acting up, though.

**Comment by TurqDevDesign** [comment]
Fantastic! I'm still not sure how any of this would cause peoples' 500 errors, but if what you said, that it only affects PHP < 5.5, is true then it shouldn't be much of an issue. Backwards compatibility is always great, but PHP and Wordpress have added many security improvements since 5.5, and it doesn't hurt to encourage updating.

**Comment by dmkjr** [comment]
@TurqDevDesign I'm nowhere near a developer, but I've been around development and WP for over a decade.  I can tell you that most users of WP know how to click a button to have a free provider install WP for you and that's about the extent.  I would bet that the users with 500 errors and provided nothing other than that, it's a user error, usage error or they are on a crappy shared host that couldn't take all the scripts they slammed into their site.

**Comment by adamtootle** [comment]
@dmkjr can you try that latest commit? That should work well with passing multiple IDs in. The default logic is OR now. So `[staff-directory cat="322,278" template=custom_4]` will query for staff in category 322 OR category 278. I added support for a `cat_relation` option in case anyone wants to use AND logic, as well as a `cat_field` option for using slugs if needed.

**Comment by dmkjr** [comment]
Sure, testing now.

**Comment by dmkjr** [comment]
Eh, it displays now.  But still displaying "featured image" and not the "staff" photo.

**Comment by adamtootle** [comment]
Ok good. So back to the template question from earlier. It is the custom template (custom_4) that's not working, right? And not the default template? Can you paste your custom_4 template so I can test that out?

**Comment by dmkjr** [comment]
shortcode = [staff-directory cat="322,278" template=custom_4]
temp = 
'

<div id="one-person">
<div class="person-photo">
<img src="[photo_url]" />
</div>

<div class="person-name"><h4>[name]</h4></div>

<div class="person-titre"><h5>[position]</h5></div>

<div class="person-number">Phone: [phone_number]</div>

<div class="person-email"><a href="/cdn-cgi/l/email-protection#5209373f333b3e0f">[email]</a></div>

</div><br>
'

**Comment by dmkjr** [comment]
`<div id="one-person">
<div class="person-photo">
<img src="[photo_url]" />
</div>
<div class="person-name"><h4>[name]</h4></div>
<div class="person-titre"><h5>[position]</h5></div>
<div class="person-number">Phone: [phone_number]</div>
<div class="person-email"><a href="/cdn-cgi/l/email-protection#5209373f333b3e0f">[email]</a></div>
</div><br>`

**Comment by dmkjr** [comment]
`
<div id="one-person">
<div class="person-photo">
<img src="[photo_url]" />
</div>
<div class="person-name"><h4>[name]</h4></div>
<div class="person-titre"><h5>[position]</h5></div>
<div class="person-number">Phone: [phone_number]</div>
<div class="person-email"><a href="/cdn-cgi/l/email-protection#5209373f333b3e0f">[email]</a></div>
</div><br>

`

**Comment by dmkjr** [comment]
'''
<div id="one-person">
<div class="person-photo">
<img src="[photo_url]" />
</div>
<div class="person-name"><h4>[name]</h4></div>
<div class="person-titre"><h5>[position]</h5></div>
<div class="person-number">Phone: [phone_number]</div>
<div class="person-email"><a href="/cdn-cgi/l/email-protection#5209373f333b3e0f">[email]</a></div>
</div><br>
'''

**Comment by adamtootle** [comment]
lol markdown can be tricky. Use 3 tick marks before and after multiple lines.

```
code here
```

**Comment by dmkjr** [comment]
```
<div id="one-person">
<div class="person-photo">
<img src="[photo_url]" />
</div>
<div class="person-name"><h4>[name]</h4></div>
<div class="person-titre"><h5>[position]</h5></div>
<div class="person-number">Phone: [phone_number]</div>
<div class="person-email"><a href="/cdn-cgi/l/email-protection#5209373f333b3e0f">[email]</a></div>
</div><br>
```

**Comment by dmkjr** [comment]
I guess I should have further stated, it's not just the featured image.  It's not displaying the name, phone number, email or any other data from the staff member.  Just has a placeholder for a staff member.

**Comment by adamtootle** [comment]
Ok. It took a few minutes to track down, but I think I have a solution.

I pasted you template in and it didn't work for me, as I'd hoped. Due to how the plugin performs the query to get staff members, it actually has to "loop" over a list of staff member results from the query. Even if the list only contains a single staff member. There's a mention of this in the plugin help section and it's included in the default custom template, but you actually need to wrap your template code in the `[staff_loop]` and `[/staff_loop]` shortcodes/tags. This would be my suggestion:

```
[staff_loop]
  <div class="one-person">
    <div class="person-photo">
      <img src="[photo_url]" />
    </div>
    <div class="person-name"><h4>[name]</h4></div>
    <div class="person-titre"><h5>[position]</h5></div>
    <div class="person-number">Phone: [phone_number]</div>
    <div class="person-email"><a href="/cdn-cgi/l/email-protection#5209373f333b3e0f">[email]</a></div>
  </div>
  <br>
[/staff_loop]
```

Notice: I changed the 'one-person' id to a class, just in case you ever display multiple staff members on a single page. ID's are meant to be unique and classes can be used multiple times, as would be the case if you ever showed two or more staff members at a time.

**Comment by adamtootle** [comment]
@dmkjr let me know if it's all working for you. I'll push an official update if so.

**Comment by dmkjr** [comment]
@adamtootle Apologize I fell asleep last night.   All seems to work well now.  That did the trick.

How would you link to each biography for each user?  So, if I want to change the template to have their name clickable to go to their biography page?  Thx again for all the work!

**Comment by dmkjr** [comment]
@adamtootle I spoke too soon.  I wasn't really awake yet.  That did not fix the issue.  The names, positions, and such appear correctly now, but the "featured image" is still showing as the staff members photo.

**Comment by dmkjr** [comment]
@adamtootle Another issue, that may help you with this one.  If you look at an individuals biography page such as, https://cityofhanahan.com/staff/ricardo-perry/ you will see that it's not loading properly, or at least I don't think so.  It doesn't flow with the template and really doesn't contain anything.  

On your older version, biography pages worked and looked good, fit right into the theme, but didn't load their staff image and such.

**Comment by TurqDevDesign** [comment]
@dmkjr in terms of the single template, the default admittedly does need to be improved. When I implemented the feature I designed the template around what I needed (see here if you're interested http://www.oxfordacademymi.com/oxford/faculty/), and then I stripped out all of my customization in order to make it more friendly for other users. Before, by default, it simply used your theme's single.php file. So, if you'd prefer your old look, you can simply copy your single.php, rename to single-staff-whateverYouWant.php, make sure it is saved in your theme's main directory, and then change the single template option, in staff directory settings, from default to your new file.

**Comment by TurqDevDesign** [comment]
Just to be clear, your file MUST start with single-staff- in order to be recognized by the plugin.

**Comment by dmkjr** [comment]
Ahh, gotcha.  I'll play with that in just a minute.  Any idea why the featured images are showing instead of the staff member photos?  I left the new plugin installed to show you two what it looks like.

**Comment by TurqDevDesign** [comment]
Yeah, I took a look at your page, I'm going to try to duplicate the issue on my local sandbox, see if I can't diagnose it.

**Comment by dmkjr** [comment]
Gotcha.  Also, I absolutely love your staff directory on your website.  That is exactly how I want to display them.  Currently, I have this.

https://cityofhanahan.com/staff-directory/

**Comment by TurqDevDesign** [comment]
Well thank you, you're welcome to use it as a reference, and if you need any help with the css just let me know (you can reach me at turqdevdesign@gmail.com), it's all custom.

**Comment by dmkjr** [comment]
Yeah, I'll shoot you an email now.  I would love to piggy back off that.  I would need to edit it slightly, but man it looks great.

**Comment by TurqDevDesign** [comment]
Ok, I'm rather confused.. `[photo]` works, it but `[photo_url]` uses the wrong post. But the strange part is that `[photo]` literally uses the same function as `[photo_url]`, just adds an image tag around it...

**Comment by adamtootle** [comment]
If it's trying to use the featured image of the current page (ie: the container post) then the loop is most likely loosing track of the current post somewhere. As in, `get_the_ID()` might be returning the page ID instead of the current staff ID at some point. I'll try to troubleshoot it. Might need to recheck those image shortcodes.

**Comment by adamtootle** [comment]
Although, @TurqDevDesign is right. Those are the same function. Are we 100% sure that one works and they aren't both broken?

**Comment by TurqDevDesign** [comment]
@adamtootle I've narrowed it down. The shortcode only breaks when it's used as an HTML attribute. If you use it outside an HTML attribute then it returns the correct URL. Inside the HTML attribute for some reason it is using the wrong loop.

**Comment by TurqDevDesign** [comment]
@adamtootle I've read issues with shortcodes in HTML attributes in previous versions (https://core.trac.wordpress.org/ticket/33102), but I think it's since been resolved. I'm still trying to resolve how we could work around this.

**Comment by adamtootle** [comment]
@TurqDevDesign yeah that's what I'm seeing too. Trying to track it down now.

**Comment by dmkjr** [comment]
I'm back around if you guys need me to test live.

**Comment by dmkjr** [comment]
@TurqDevDesign Austin, I'm attempting to create the single page now.  However, my theme doesn't call for a single.php in the theme directory.  I see a page.php perhaps?  There are some that start with single but it's theme specific, singe-lsvrdocument.php, single-lsvrevent.php and so forth.

I also have an article.php in the theme folder.

**Comment by TurqDevDesign** [comment]
@dmkjr is it a child theme? if so then you need the single.php from your parent theme.

**Comment by dmkjr** [comment]
It's not a child theme.  
<img width="281" alt="screen shot 2016-11-20 at 12 53 57 pm" src="https://cloud.githubusercontent.com/assets/662675/20464941/7a259e50-af20-11e6-82ff-df720e57b0b7.png">

**Comment by TurqDevDesign** [comment]
Here is the template hierarchy for single posts https://developer.wordpress.org/themes/basics/template-hierarchy/#single-post . I'd assume that if you don't have a single.php then your theme must use custom post types for the single posts.

**Comment by dmkjr** [comment]
Does this make any sense for that?

<img width="939" alt="screen shot 2016-11-20 at 1 09 11 pm" src="https://cloud.githubusercontent.com/assets/662675/20465052/9a60e858-af22-11e6-8d93-aa3bda783b47.png">

**Comment by TurqDevDesign** [comment]
What do you have set under Settings / Reading?

**Comment by TurqDevDesign** [comment]
All you need to do is figure out which of those 4 single-*.php files was being used for the single post, and then use that. You could just try them all and see which looks best if you want.

**Comment by dmkjr** [comment]
I have opened up the single-lsvrnotice.php.

Now, if I understand correctly I should copy and rename to single-staff-template.php with the same content from the regular single-lsvrnotice.php?

**Comment by dmkjr** [comment]
I have named the single-lsvrnotice.php to single-staff-template.php and it didn't change the look or output of https://cityofhanahan.com/staff/dennis-turner/

**Comment by TurqDevDesign** [comment]
@dmkjr Correct, just duplicate it, rename it, and select it in your settings dropdown.

**Comment by TurqDevDesign** [comment]
@adamtootle Do you have any ideas? being a Wordpress bug it seems like it'd be best to just discontinue the `[photo_url]` shortcode, in favor of `[photo]`, and just add options to `[photo]` for a title, alt, class, and id tag.

**Comment by TurqDevDesign** [comment]
The only real issue is that it'd probably break many peoples' custom templates.

**Comment by dmkjr** [comment]
Forgive my ignorance here, but on the drop down.... it's only selectable for pages that I have created in WP, not the theme files.  Am I missing something?

**Comment by TurqDevDesign** [comment]
In your sidebar, under Staff > Settings. There is a heading **Single profile templates**. Under that heading there is a dropdown that should say 'Default', you want to change that to your new file.

**Comment by dmkjr** [comment]
Yep, told you it was my ignorance.  All is well now.  Thx!  I'll need to add a couple things, but looks good now.

https://cityofhanahan.com/staff/dennis-turner/

**Comment by dmkjr** [comment]
@TurqDevDesign To get the elements from your single-staff, what code should be copied into my "single-staff-template"?  I've been playing around with it, but just crashed my web server and had to reboot after doing something wrong with the php left running.

**Comment by TurqDevDesign** [comment]
This is the single template that I use, pretty much the same as the
default. If you want to style it you can inspect my css on the page. I'd
just give it to you but I'm a bit busy with some other things and I don't
have the time right at the moment to sift through it all for the selectors
specific to this page. If you can wait a day or two then I could find some
time to get it to you, but it might just be easier for you to just inspect
it and play it by ear. Especially since your layout is a bit different
anyway.

**Comment by TurqDevDesign** [comment]
@dmkjr I sent you an email.

**Comment by dmkjr** [comment]
@TurqDevDesign Thanks.  I'm just now starting to play with it.

**Comment by dmkjr** [comment]
I attempted to create a hyperlink to the email using the [email] shortcode.  Here is what I did.  

`<a href="mailto:[email]"><?php echo do_shortcode('[email]'); ?></a>`

It created a link, but did not link appropriately.  Is there another method to call for the email address?

**Comment by adamtootle** [comment]
As of right now I can confirm that shortcodes nested inside html attributes are called before any other shortcodes, which includes `[staff_loop]` and `[/staff_loop]`. As a result, any references to the current post (ie: `get_the_ID()` or `has_post_thumbnail()`) within the shortcode is _outside_ the staff query loop and referencing whatever the current post may be. In my test case and what I believe it happening elsewhere is that the current page gets referenced. I've been digging through the WP source trying to figure out if it's a bug or if there's a way around that. No luck yet. Unfortunately, it's looking like the cleverness of converting the template tags to official WP shortcodes introduced this. If I can't find a work around tonight I may revert part of that back to `str_replace()` or something else that manually replaces the shortcodes. I won't be able to spend as much time this coming week as I've spent on this over the weekend and I don't want to leave this stuff in a non-functioning state.

**Comment by dmkjr** [comment]
Thank you @adamtootle 

Will the custom template option still be available for the staff biographies?  Been working on that most of the day, cleaning things up and getting it looking like I want it.

**Comment by TurqDevDesign** [comment]
@adamtootle Have you begun work on the str_replace() fallback? If not, I could probably begin work on it right now.

**Comment by adamtootle** [comment]
@TurqDevDesign well actually, reverting back on that would break usage of `do_shortcode()` in the single template. I had that realization today. The custom fields need to remain registered as shortcodes. Until we can find a work around we may need to prefer usage of the `[photo]` shortcode, rather than relying on `<img src="[photo_url]" />`. _But_, we may can take advantage of that. This is untested (and unsupported at the moment), but we should be able to pass in attributes like `[photo class="staff-portrait"]` since it's an official shortcode. This could allow control over things that a user may want by using a custom `<img />` tag and `[photo_ur]`. I think I may want to move that direction for now.

So yes @dmkjr, single templates will still function as expected with the next commit. You may need to tweak how you use shortcodes for the image, unless I have an epiphany within the next 12 hours or so.

**Comment by TurqDevDesign** [comment]
@adamtootle Actually, I'm working on a fix right now to preserve `[photo_url]`, my idea keeps the integrity of built-in Wordpress shortcodes, but works around the bug using some simple `preg_match()` and `str_replace()`. I wish I had thought of it yesterday, but I've been fighting off a cold for the past week or so, so my mind has not been anywhere near peak efficiency. But, I'm finally feeling much better today, so I should be able to get this done within the next hour or so assuming no unforeseen issues.

**Comment by TurqDevDesign** [comment]
@adamtootle I've fixed the issue in my pull request #15

**Comment by dmkjr** [comment]
Is there a method to download with your changes?

**Comment by TurqDevDesign** [comment]
Yes, just visit my fork from my pull request #15

**Comment by dmkjr** [comment]
@TurqDevDesign Good news!  This fixes majority of the problems and the photo_url works again.  There is another issue with some HTML and displaying a user out of the category.

For example, if you visit https://cityofhanahan.com/government/police-department/
and look on the left sidebar, you will see the user "Travis Dodd" that is randomly thrown into then mix.  Also, seems to break the container for the HTML layout.  You'll see a few names down the background changes.  Good news is the images appear correctly now though!

**Comment by dmkjr** [comment]
So I spoke too soon.  My code was the problem.  It's fixed and all works well!  Thank yo!

**Comment by TurqDevDesign** [comment]
Perfect! Glad I could help.

**Comment by dmkjr** [comment]
Are you two going to start implementing any other changes?  I have a few ideas if interested.

**Comment by adamtootle** [comment]
@TurqDevDesign I'm going to take a look at the PR in the next few minutes.

@dmkjr I go through spurts of work on this plugin throughout the year. I'm going to try to give it some more attention going forward. Just file your requests separately as issues here and I'd be glad to take a look!

**Comment by dmkjr** [comment]
@TurqDevDesign Quick question.  What page would need to be edited for a category page that self generates by the category?  For example, 

https://cityofhanahan.com/staff-categories/police-department/school-resource-officers-police-department/

What page would I edit to edit the output of that?  I want to make it similar to my other staff directory pages.

Thanks,
David

**Comment by TurqDevDesign** [comment]
@dmkjr Category hierarchies can be found here https://developer.wordpress.org/themes/basics/template-hierarchy/#category . Also, I'm happy to answer any questions you may have, but for questions unrelated to the reported issue I'd appreciate if you could just send me a personal e-mail.

**Comment by adamtootle** [comment]
It sounds like we're all good here. I'm going to close this for now and push v1.1.1 to wordpress.org. Thanks for all the help debugging these issues, guys!
